# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\plot1d.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(987, 453)
        Dialog.setSizeGripEnabled(False)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = PlotWidget(Dialog)
        self.widget.setObjectName("widget")
        self.horizontalLayout.addWidget(self.widget)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(250, 16777215))
        self.tabWidget.setObjectName("tabWidget")
        self.tabInteraction = QtWidgets.QWidget()
        self.tabInteraction.setMinimumSize(QtCore.QSize(0, 0))
        self.tabInteraction.setObjectName("tabInteraction")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabInteraction)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayoutInteraction = QtWidgets.QVBoxLayout()
        self.verticalLayoutInteraction.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayoutInteraction.setObjectName("verticalLayoutInteraction")
        self.groupBoxDisplay = QtWidgets.QGroupBox(self.tabInteraction)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxDisplay.setFont(font)
        self.groupBoxDisplay.setObjectName("groupBoxDisplay")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBoxDisplay)
        self.verticalLayout_4.setContentsMargins(1, 5, 1, 1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayoutLog = QtWidgets.QHBoxLayout()
        self.horizontalLayoutLog.setObjectName("horizontalLayoutLog")
        self.checkBoxLogX = QtWidgets.QCheckBox(self.groupBoxDisplay)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.checkBoxLogX.setFont(font)
        self.checkBoxLogX.setObjectName("checkBoxLogX")
        self.horizontalLayoutLog.addWidget(self.checkBoxLogX)
        self.checkBoxLogY = QtWidgets.QCheckBox(self.groupBoxDisplay)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.checkBoxLogY.setFont(font)
        self.checkBoxLogY.setObjectName("checkBoxLogY")
        self.horizontalLayoutLog.addWidget(self.checkBoxLogY)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutLog.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayoutLog)
        self.checkBoxSymbol = QtWidgets.QCheckBox(self.groupBoxDisplay)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.checkBoxSymbol.setFont(font)
        self.checkBoxSymbol.setObjectName("checkBoxSymbol")
        self.verticalLayout_4.addWidget(self.checkBoxSymbol)
        self.checkBoxCrossHair = QtWidgets.QCheckBox(self.groupBoxDisplay)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.checkBoxCrossHair.setFont(font)
        self.checkBoxCrossHair.setChecked(False)
        self.checkBoxCrossHair.setObjectName("checkBoxCrossHair")
        self.verticalLayout_4.addWidget(self.checkBoxCrossHair)
        self.horizontalLayoutFontSize = QtWidgets.QHBoxLayout()
        self.horizontalLayoutFontSize.setObjectName("horizontalLayoutFontSize")
        self.labelFontSize = QtWidgets.QLabel(self.groupBoxDisplay)
        self.labelFontSize.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.labelFontSize.setFont(font)
        self.labelFontSize.setObjectName("labelFontSize")
        self.horizontalLayoutFontSize.addWidget(self.labelFontSize)
        self.spinBoxFontSize = QtWidgets.QSpinBox(self.groupBoxDisplay)
        self.spinBoxFontSize.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.spinBoxFontSize.setFont(font)
        self.spinBoxFontSize.setProperty("value", 12)
        self.spinBoxFontSize.setObjectName("spinBoxFontSize")
        self.horizontalLayoutFontSize.addWidget(self.spinBoxFontSize)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutFontSize.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayoutFontSize)
        self.verticalLayoutInteraction.addWidget(self.groupBoxDisplay)
        self.groupBoxPlotDataItem = QtWidgets.QGroupBox(self.tabInteraction)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxPlotDataItem.setFont(font)
        self.groupBoxPlotDataItem.setObjectName("groupBoxPlotDataItem")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBoxPlotDataItem)
        self.verticalLayout_3.setContentsMargins(1, 5, 1, 1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayoutPlotDataItem = QtWidgets.QVBoxLayout()
        self.verticalLayoutPlotDataItem.setObjectName("verticalLayoutPlotDataItem")
        self.radioButtonFitNone = QtWidgets.QRadioButton(self.groupBoxPlotDataItem)
        self.radioButtonFitNone.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.radioButtonFitNone.setFont(font)
        self.radioButtonFitNone.setChecked(True)
        self.radioButtonFitNone.setObjectName("radioButtonFitNone")
        self.verticalLayoutPlotDataItem.addWidget(self.radioButtonFitNone)
        self.verticalLayout_3.addLayout(self.verticalLayoutPlotDataItem)
        self.verticalLayoutInteraction.addWidget(self.groupBoxPlotDataItem)
        self.groupBoxCurveInteraction = QtWidgets.QGroupBox(self.tabInteraction)
        self.groupBoxCurveInteraction.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxCurveInteraction.setFont(font)
        self.groupBoxCurveInteraction.setObjectName("groupBoxCurveInteraction")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBoxCurveInteraction)
        self.verticalLayout_2.setContentsMargins(1, 5, 1, 1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBoxCalculus = QtWidgets.QGroupBox(self.groupBoxCurveInteraction)
        self.groupBoxCalculus.setObjectName("groupBoxCalculus")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBoxCalculus)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBoxDifferentiate = QtWidgets.QCheckBox(self.groupBoxCalculus)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBoxDifferentiate.setFont(font)
        self.checkBoxDifferentiate.setObjectName("checkBoxDifferentiate")
        self.horizontalLayout_3.addWidget(self.checkBoxDifferentiate)
        self.checkBoxIntegrate = QtWidgets.QCheckBox(self.groupBoxCalculus)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBoxIntegrate.setFont(font)
        self.checkBoxIntegrate.setObjectName("checkBoxIntegrate")
        self.horizontalLayout_3.addWidget(self.checkBoxIntegrate)
        self.verticalLayout_2.addWidget(self.groupBoxCalculus)
        self.groupBoxFFT = QtWidgets.QGroupBox(self.groupBoxCurveInteraction)
        self.groupBoxFFT.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxFFT.setFont(font)
        self.groupBoxFFT.setObjectName("groupBoxFFT")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBoxFFT)
        self.horizontalLayout_4.setContentsMargins(1, 5, 1, 1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButtonFFT = QtWidgets.QRadioButton(self.groupBoxFFT)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.radioButtonFFT.setFont(font)
        self.radioButtonFFT.setObjectName("radioButtonFFT")
        self.buttonGroup = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButtonFFT)
        self.horizontalLayout_4.addWidget(self.radioButtonFFT)
        self.radioButtonFFTnoDC = QtWidgets.QRadioButton(self.groupBoxFFT)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.radioButtonFFTnoDC.setFont(font)
        self.radioButtonFFTnoDC.setObjectName("radioButtonFFTnoDC")
        self.buttonGroup.addButton(self.radioButtonFFTnoDC)
        self.horizontalLayout_4.addWidget(self.radioButtonFFTnoDC)
        self.radioButtonIFFT = QtWidgets.QRadioButton(self.groupBoxFFT)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.radioButtonIFFT.setFont(font)
        self.radioButtonIFFT.setObjectName("radioButtonIFFT")
        self.buttonGroup.addButton(self.radioButtonIFFT)
        self.horizontalLayout_4.addWidget(self.radioButtonIFFT)
        self.verticalLayout_2.addWidget(self.groupBoxFFT)
        self.groupBoxFilering = QtWidgets.QGroupBox(self.groupBoxCurveInteraction)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxFilering.setFont(font)
        self.groupBoxFilering.setObjectName("groupBoxFilering")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBoxFilering)
        self.verticalLayout_6.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayoutFilteringModel = QtWidgets.QVBoxLayout()
        self.verticalLayoutFilteringModel.setObjectName("verticalLayoutFilteringModel")
        self.verticalLayout_6.addLayout(self.verticalLayoutFilteringModel)
        self.verticalLayout_2.addWidget(self.groupBoxFilering)
        self.groupBoxFit = QtWidgets.QGroupBox(self.groupBoxCurveInteraction)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxFit.setFont(font)
        self.groupBoxFit.setObjectName("groupBoxFit")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBoxFit)
        self.verticalLayout_5.setContentsMargins(1, 5, 1, 1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayoutFitModel = QtWidgets.QVBoxLayout()
        self.verticalLayoutFitModel.setObjectName("verticalLayoutFitModel")
        self.verticalLayout_5.addLayout(self.verticalLayoutFitModel)
        self.verticalLayout_2.addWidget(self.groupBoxFit)
        self.verticalLayoutInteraction.addWidget(self.groupBoxCurveInteraction)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayoutInteraction.addItem(spacerItem2)
        self.labelCoordinate = QtWidgets.QLabel(self.tabInteraction)
        self.labelCoordinate.setMinimumSize(QtCore.QSize(125, 0))
        self.labelCoordinate.setObjectName("labelCoordinate")
        self.verticalLayoutInteraction.addWidget(self.labelCoordinate)
        self.verticalLayout.addLayout(self.verticalLayoutInteraction)
        self.tabWidget.addTab(self.tabInteraction, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBoxDisplay.setTitle(_translate("Dialog", "Display"))
        self.checkBoxLogX.setText(_translate("Dialog", "log x"))
        self.checkBoxLogY.setText(_translate("Dialog", "log y"))
        self.checkBoxSymbol.setText(_translate("Dialog", "symbol (fastest without)"))
        self.checkBoxCrossHair.setText(_translate("Dialog", "cross hair (fastest without)"))
        self.labelFontSize.setText(_translate("Dialog", "Font size:"))
        self.groupBoxPlotDataItem.setTitle(_translate("Dialog", "Select curve"))
        self.radioButtonFitNone.setText(_translate("Dialog", "None"))
        self.groupBoxCurveInteraction.setTitle(_translate("Dialog", "Curve interaction"))
        self.groupBoxCalculus.setTitle(_translate("Dialog", "Calculus"))
        self.checkBoxDifferentiate.setText(_translate("Dialog", "differentiate"))
        self.checkBoxIntegrate.setText(_translate("Dialog", "integrate"))
        self.groupBoxFFT.setTitle(_translate("Dialog", "FFT"))
        self.radioButtonFFT.setText(_translate("Dialog", "FFT"))
        self.radioButtonFFTnoDC.setText(_translate("Dialog", "FFT (no DC)"))
        self.radioButtonIFFT.setText(_translate("Dialog", "IFFT"))
        self.groupBoxFilering.setTitle(_translate("Dialog", "Filtering"))
        self.groupBoxFit.setTitle(_translate("Dialog", "Fit"))
        self.labelCoordinate.setText(_translate("Dialog", "<html><head/><body><p>x:<br/>y:</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabInteraction), _translate("Dialog", "Interaction"))

from ..ui.plot_widget import PlotWidget
