# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\scripts\pyplotter\pyplotter\ui\dialogLiveplot.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LivePlot(object):
    def setupUi(self, LivePlot):
        LivePlot.setObjectName("LivePlot")
        LivePlot.resize(310, 378)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(LivePlot)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBoxSelection = QtWidgets.QGroupBox(LivePlot)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxSelection.setFont(font)
        self.groupBoxSelection.setObjectName("groupBoxSelection")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBoxSelection)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayoutLivePlot1 = QtWidgets.QHBoxLayout()
        self.horizontalLayoutLivePlot1.setObjectName("horizontalLayoutLivePlot1")
        self.pushButtonLivePlot = QtWidgets.QPushButton(self.groupBoxSelection)
        self.pushButtonLivePlot.setEnabled(True)
        self.pushButtonLivePlot.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonLivePlot.setFont(font)
        self.pushButtonLivePlot.setObjectName("pushButtonLivePlot")
        self.horizontalLayoutLivePlot1.addWidget(self.pushButtonLivePlot)
        self.verticalLayout_6.addLayout(self.horizontalLayoutLivePlot1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelLivePlotRefreshRate = QtWidgets.QLabel(self.groupBoxSelection)
        self.labelLivePlotRefreshRate.setMinimumSize(QtCore.QSize(168, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.labelLivePlotRefreshRate.setFont(font)
        self.labelLivePlotRefreshRate.setObjectName("labelLivePlotRefreshRate")
        self.horizontalLayout.addWidget(self.labelLivePlotRefreshRate)
        self.spinBoxLivePlotRefreshRate = QtWidgets.QSpinBox(self.groupBoxSelection)
        self.spinBoxLivePlotRefreshRate.setEnabled(True)
        self.spinBoxLivePlotRefreshRate.setMinimumSize(QtCore.QSize(25, 0))
        self.spinBoxLivePlotRefreshRate.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.spinBoxLivePlotRefreshRate.setFont(font)
        self.spinBoxLivePlotRefreshRate.setObjectName("spinBoxLivePlotRefreshRate")
        self.horizontalLayout.addWidget(self.spinBoxLivePlotRefreshRate)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addWidget(self.groupBoxSelection)
        self.groupBoxInfo = QtWidgets.QGroupBox(LivePlot)
        self.groupBoxInfo.setMinimumSize(QtCore.QSize(290, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxInfo.setFont(font)
        self.groupBoxInfo.setObjectName("groupBoxInfo")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBoxInfo)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayoutLivePlotDatabasePath = QtWidgets.QHBoxLayout()
        self.horizontalLayoutLivePlotDatabasePath.setObjectName("horizontalLayoutLivePlotDatabasePath")
        self.labelLivePlotDatabasePath = QtWidgets.QLabel(self.groupBoxInfo)
        self.labelLivePlotDatabasePath.setMinimumSize(QtCore.QSize(168, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.labelLivePlotDatabasePath.setFont(font)
        self.labelLivePlotDatabasePath.setObjectName("labelLivePlotDatabasePath")
        self.horizontalLayoutLivePlotDatabasePath.addWidget(self.labelLivePlotDatabasePath)
        self.labelLivePlotDatabasePathInfo = QtWidgets.QLabel(self.groupBoxInfo)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.labelLivePlotDatabasePathInfo.setFont(font)
        self.labelLivePlotDatabasePathInfo.setText("")
        self.labelLivePlotDatabasePathInfo.setObjectName("labelLivePlotDatabasePathInfo")
        self.horizontalLayoutLivePlotDatabasePath.addWidget(self.labelLivePlotDatabasePathInfo)
        self.verticalLayout_7.addLayout(self.horizontalLayoutLivePlotDatabasePath)
        self.horizontalLayoutLivePlotDatabase = QtWidgets.QHBoxLayout()
        self.horizontalLayoutLivePlotDatabase.setObjectName("horizontalLayoutLivePlotDatabase")
        self.labelLivePlotDatabaseName = QtWidgets.QLabel(self.groupBoxInfo)
        self.labelLivePlotDatabaseName.setMinimumSize(QtCore.QSize(168, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.labelLivePlotDatabaseName.setFont(font)
        self.labelLivePlotDatabaseName.setObjectName("labelLivePlotDatabaseName")
        self.horizontalLayoutLivePlotDatabase.addWidget(self.labelLivePlotDatabaseName)
        self.labelLivePlotDatabaseNameInfo = QtWidgets.QLabel(self.groupBoxInfo)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.labelLivePlotDatabaseNameInfo.setFont(font)
        self.labelLivePlotDatabaseNameInfo.setText("")
        self.labelLivePlotDatabaseNameInfo.setObjectName("labelLivePlotDatabaseNameInfo")
        self.horizontalLayoutLivePlotDatabase.addWidget(self.labelLivePlotDatabaseNameInfo)
        self.verticalLayout_7.addLayout(self.horizontalLayoutLivePlotDatabase)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.labelLivePlotInProgress = QtWidgets.QLabel(self.groupBoxInfo)
        self.labelLivePlotInProgress.setMinimumSize(QtCore.QSize(168, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.labelLivePlotInProgress.setFont(font)
        self.labelLivePlotInProgress.setObjectName("labelLivePlotInProgress")
        self.horizontalLayout_8.addWidget(self.labelLivePlotInProgress)
        self.labelLivePlotInProgressState = QtWidgets.QLabel(self.groupBoxInfo)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.labelLivePlotInProgressState.setFont(font)
        self.labelLivePlotInProgressState.setObjectName("labelLivePlotInProgressState")
        self.horizontalLayout_8.addWidget(self.labelLivePlotInProgressState)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelLivePlotRunid = QtWidgets.QLabel(self.groupBoxInfo)
        self.labelLivePlotRunid.setMinimumSize(QtCore.QSize(168, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.labelLivePlotRunid.setFont(font)
        self.labelLivePlotRunid.setObjectName("labelLivePlotRunid")
        self.horizontalLayout_6.addWidget(self.labelLivePlotRunid)
        self.labelLivePlotRunidid = QtWidgets.QLabel(self.groupBoxInfo)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.labelLivePlotRunidid.setFont(font)
        self.labelLivePlotRunidid.setText("")
        self.labelLivePlotRunidid.setObjectName("labelLivePlotRunidid")
        self.horizontalLayout_6.addWidget(self.labelLivePlotRunidid)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelLivePlotRunName = QtWidgets.QLabel(self.groupBoxInfo)
        self.labelLivePlotRunName.setMinimumSize(QtCore.QSize(168, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.labelLivePlotRunName.setFont(font)
        self.labelLivePlotRunName.setObjectName("labelLivePlotRunName")
        self.horizontalLayout_4.addWidget(self.labelLivePlotRunName)
        self.labelLivePlotRunNameInfo = QtWidgets.QLabel(self.groupBoxInfo)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.labelLivePlotRunNameInfo.setFont(font)
        self.labelLivePlotRunNameInfo.setText("")
        self.labelLivePlotRunNameInfo.setObjectName("labelLivePlotRunNameInfo")
        self.horizontalLayout_4.addWidget(self.labelLivePlotRunNameInfo)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.labelLivePlotNbPoint = QtWidgets.QLabel(self.groupBoxInfo)
        self.labelLivePlotNbPoint.setMinimumSize(QtCore.QSize(168, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.labelLivePlotNbPoint.setFont(font)
        self.labelLivePlotNbPoint.setObjectName("labelLivePlotNbPoint")
        self.horizontalLayout_15.addWidget(self.labelLivePlotNbPoint)
        self.labelLivePlotNbPointInfo = QtWidgets.QLabel(self.groupBoxInfo)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.labelLivePlotNbPointInfo.setFont(font)
        self.labelLivePlotNbPointInfo.setText("")
        self.labelLivePlotNbPointInfo.setObjectName("labelLivePlotNbPointInfo")
        self.horizontalLayout_15.addWidget(self.labelLivePlotNbPointInfo)
        self.verticalLayout_7.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.labelLivePlotInfo = QtWidgets.QLabel(self.groupBoxInfo)
        self.labelLivePlotInfo.setMinimumSize(QtCore.QSize(168, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.labelLivePlotInfo.setFont(font)
        self.labelLivePlotInfo.setObjectName("labelLivePlotInfo")
        self.horizontalLayout_16.addWidget(self.labelLivePlotInfo)
        self.labelLivePlotInfoInfo = QtWidgets.QLabel(self.groupBoxInfo)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.labelLivePlotInfoInfo.setFont(font)
        self.labelLivePlotInfoInfo.setText("")
        self.labelLivePlotInfoInfo.setObjectName("labelLivePlotInfoInfo")
        self.horizontalLayout_16.addWidget(self.labelLivePlotInfoInfo)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.labelLivePlotLastRefresh = QtWidgets.QLabel(self.groupBoxInfo)
        self.labelLivePlotLastRefresh.setMinimumSize(QtCore.QSize(168, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.labelLivePlotLastRefresh.setFont(font)
        self.labelLivePlotLastRefresh.setObjectName("labelLivePlotLastRefresh")
        self.horizontalLayout_9.addWidget(self.labelLivePlotLastRefresh)
        self.labelLivePlotLastRefreshInfo = QtWidgets.QLabel(self.groupBoxInfo)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.labelLivePlotLastRefreshInfo.setFont(font)
        self.labelLivePlotLastRefreshInfo.setText("")
        self.labelLivePlotLastRefreshInfo.setObjectName("labelLivePlotLastRefreshInfo")
        self.horizontalLayout_9.addWidget(self.labelLivePlotLastRefreshInfo)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.labelLivePlotSinceLastRefresh = QtWidgets.QLabel(self.groupBoxInfo)
        self.labelLivePlotSinceLastRefresh.setMinimumSize(QtCore.QSize(168, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.labelLivePlotSinceLastRefresh.setFont(font)
        self.labelLivePlotSinceLastRefresh.setObjectName("labelLivePlotSinceLastRefresh")
        self.horizontalLayout_11.addWidget(self.labelLivePlotSinceLastRefresh)
        self.labelLivePlotSinceLastRefreshInfo = QtWidgets.QLabel(self.groupBoxInfo)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.labelLivePlotSinceLastRefreshInfo.setFont(font)
        self.labelLivePlotSinceLastRefreshInfo.setText("")
        self.labelLivePlotSinceLastRefreshInfo.setObjectName("labelLivePlotSinceLastRefreshInfo")
        self.horizontalLayout_11.addWidget(self.labelLivePlotSinceLastRefreshInfo)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.labelLivePlotLastUpdate = QtWidgets.QLabel(self.groupBoxInfo)
        self.labelLivePlotLastUpdate.setMinimumSize(QtCore.QSize(168, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.labelLivePlotLastUpdate.setFont(font)
        self.labelLivePlotLastUpdate.setObjectName("labelLivePlotLastUpdate")
        self.horizontalLayout_7.addWidget(self.labelLivePlotLastUpdate)
        self.labelLivePlotLastUpdateInfo = QtWidgets.QLabel(self.groupBoxInfo)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.labelLivePlotLastUpdateInfo.setFont(font)
        self.labelLivePlotLastUpdateInfo.setText("")
        self.labelLivePlotLastUpdateInfo.setObjectName("labelLivePlotLastUpdateInfo")
        self.horizontalLayout_7.addWidget(self.labelLivePlotLastUpdateInfo)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.labelLivePlotSinceLastUpdate = QtWidgets.QLabel(self.groupBoxInfo)
        self.labelLivePlotSinceLastUpdate.setMinimumSize(QtCore.QSize(168, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.labelLivePlotSinceLastUpdate.setFont(font)
        self.labelLivePlotSinceLastUpdate.setObjectName("labelLivePlotSinceLastUpdate")
        self.horizontalLayout_10.addWidget(self.labelLivePlotSinceLastUpdate)
        self.labelLivePlotSinceLastUpdateInfo = QtWidgets.QLabel(self.groupBoxInfo)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.labelLivePlotSinceLastUpdateInfo.setFont(font)
        self.labelLivePlotSinceLastUpdateInfo.setText("")
        self.labelLivePlotSinceLastUpdateInfo.setObjectName("labelLivePlotSinceLastUpdateInfo")
        self.horizontalLayout_10.addWidget(self.labelLivePlotSinceLastUpdateInfo)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.verticalLayout_3.addWidget(self.groupBoxInfo)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)

        self.retranslateUi(LivePlot)
        QtCore.QMetaObject.connectSlotsByName(LivePlot)

    def retranslateUi(self, LivePlot):
        _translate = QtCore.QCoreApplication.translate
        LivePlot.setWindowTitle(_translate("LivePlot", "Liveplot"))
        self.groupBoxSelection.setTitle(_translate("LivePlot", "Selection"))
        self.pushButtonLivePlot.setText(_translate("LivePlot", "Select database"))
        self.labelLivePlotRefreshRate.setToolTip(_translate("LivePlot", "If put to 0s, stop the liveploting"))
        self.labelLivePlotRefreshRate.setText(_translate("LivePlot", "Refresh rate:"))
        self.spinBoxLivePlotRefreshRate.setToolTip(_translate("LivePlot", "If put to 0s, stop the liveploting"))
        self.spinBoxLivePlotRefreshRate.setSuffix(_translate("LivePlot", " s"))
        self.groupBoxInfo.setTitle(_translate("LivePlot", "Info"))
        self.labelLivePlotDatabasePath.setText(_translate("LivePlot", "Current database path:"))
        self.labelLivePlotDatabaseName.setText(_translate("LivePlot", "Current database Name:"))
        self.labelLivePlotInProgress.setText(_translate("LivePlot", "Measurement in progress:"))
        self.labelLivePlotInProgressState.setText(_translate("LivePlot", "False"))
        self.labelLivePlotRunid.setText(_translate("LivePlot", "Run id:"))
        self.labelLivePlotRunName.setText(_translate("LivePlot", "Run name:"))
        self.labelLivePlotNbPoint.setText(_translate("LivePlot", "Nb point:"))
        self.labelLivePlotInfo.setText(_translate("LivePlot", "Information:"))
        self.labelLivePlotLastRefresh.setText(_translate("LivePlot", "Time last refresh:"))
        self.labelLivePlotSinceLastRefresh.setText(_translate("LivePlot", "Time since last refresh:"))
        self.labelLivePlotLastUpdate.setText(_translate("LivePlot", "Time last data cache update:"))
        self.labelLivePlotSinceLastUpdate.setText(_translate("LivePlot", "Time since last data cache update:"))
