# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 766)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelPath = QtWidgets.QHBoxLayout()
        self.labelPath.setObjectName("labelPath")
        self.verticalLayout_3.addLayout(self.labelPath)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setMinimumSize(QtCore.QSize(1000, 0))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter_2 = QtWidgets.QSplitter(self.layoutWidget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.labelFolder = QtWidgets.QLabel(self.layoutWidget_2)
        self.labelFolder.setObjectName("labelFolder")
        self.verticalLayout_5.addWidget(self.labelFolder)
        self.listWidgetFolder = QtWidgets.QListWidget(self.layoutWidget_2)
        self.listWidgetFolder.setObjectName("listWidgetFolder")
        self.verticalLayout_5.addWidget(self.listWidgetFolder)
        self.layoutWidget_3 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.labelDataBase = QtWidgets.QLabel(self.layoutWidget_3)
        self.labelDataBase.setObjectName("labelDataBase")
        self.verticalLayout_11.addWidget(self.labelDataBase)
        self.tableWidgetDataBase = QtWidgets.QTableWidget(self.layoutWidget_3)
        self.tableWidgetDataBase.setColumnCount(7)
        self.tableWidgetDataBase.setObjectName("tableWidgetDataBase")
        self.tableWidgetDataBase.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDataBase.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDataBase.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDataBase.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDataBase.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDataBase.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDataBase.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDataBase.setHorizontalHeaderItem(6, item)
        self.tableWidgetDataBase.horizontalHeader().setDefaultSectionSize(80)
        self.tableWidgetDataBase.horizontalHeader().setMinimumSectionSize(32)
        self.tableWidgetDataBase.horizontalHeader().setStretchLastSection(False)
        self.tableWidgetDataBase.verticalHeader().setVisible(False)
        self.verticalLayout_11.addWidget(self.tableWidgetDataBase)
        self.verticalLayout.addWidget(self.splitter_2)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter_3 = QtWidgets.QSplitter(self.layoutWidget1)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter_3)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.labelParameter = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelParameter.setObjectName("labelParameter")
        self.verticalLayout_6.addWidget(self.labelParameter)
        self.tableWidgetParameters = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.tableWidgetParameters.setObjectName("tableWidgetParameters")
        self.tableWidgetParameters.setColumnCount(3)
        self.tableWidgetParameters.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetParameters.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetParameters.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetParameters.setHorizontalHeaderItem(2, item)
        self.verticalLayout_6.addWidget(self.tableWidgetParameters)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.splitter_3)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.labelMetadata = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.labelMetadata.setObjectName("labelMetadata")
        self.verticalLayout_7.addWidget(self.labelMetadata)
        self.listWidgetMetadata = QtWidgets.QListWidget(self.verticalLayoutWidget_2)
        self.listWidgetMetadata.setObjectName("listWidgetMetadata")
        self.verticalLayout_7.addWidget(self.listWidgetMetadata)
        self.verticalLayout_2.addWidget(self.splitter_3)
        self.verticalLayout_3.addWidget(self.splitter)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Plotter"))
        self.labelFolder.setText(_translate("MainWindow", "Browse folder:"))
        self.labelDataBase.setText(_translate("MainWindow", "Browse dataBase:"))
        self.tableWidgetDataBase.setSortingEnabled(True)
        item = self.tableWidgetDataBase.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "run id"))
        item = self.tableWidgetDataBase.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "experiment"))
        item = self.tableWidgetDataBase.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "sample"))
        item = self.tableWidgetDataBase.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "name"))
        item = self.tableWidgetDataBase.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "started"))
        item = self.tableWidgetDataBase.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "completed"))
        item = self.tableWidgetDataBase.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "records"))
        self.labelParameter.setText(_translate("MainWindow", "Browse parameters:"))
        item = self.tableWidgetParameters.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "plotted"))
        item = self.tableWidgetParameters.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "axis"))
        item = self.tableWidgetParameters.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "unit"))
        self.labelMetadata.setText(_translate("MainWindow", "Browse metadata:"))

