# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plot2d.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(987, 358)
        Dialog.setSizeGripEnabled(False)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = PlotWidget(Dialog)
        self.widget.setMinimumSize(QtCore.QSize(700, 0))
        self.widget.setObjectName("widget")
        self.horizontalLayout.addWidget(self.widget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.histWidget = HistogramLUTWidget(Dialog)
        self.histWidget.setObjectName("histWidget")
        self.verticalLayout.addWidget(self.histWidget)
        self.plot2dzLabel = QtWidgets.QLabel(Dialog)
        self.plot2dzLabel.setObjectName("plot2dzLabel")
        self.verticalLayout.addWidget(self.plot2dzLabel)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.comboBoxcm = QtWidgets.QComboBox(Dialog)
        self.comboBoxcm.setObjectName("comboBoxcm")
        self.horizontalLayout_4.addWidget(self.comboBoxcm)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.checkBoxSwapxy = QtWidgets.QCheckBox(Dialog)
        self.checkBoxSwapxy.setObjectName("checkBoxSwapxy")
        self.verticalLayout_2.addWidget(self.checkBoxSwapxy)
        self.checkBoxInvert = QtWidgets.QCheckBox(Dialog)
        self.checkBoxInvert.setObjectName("checkBoxInvert")
        self.verticalLayout_2.addWidget(self.checkBoxInvert)
        self.checkBoxCrossHair = QtWidgets.QCheckBox(Dialog)
        self.checkBoxCrossHair.setChecked(False)
        self.checkBoxCrossHair.setObjectName("checkBoxCrossHair")
        self.verticalLayout_2.addWidget(self.checkBoxCrossHair)
        self.checkBoxDrawIsoCurve = QtWidgets.QCheckBox(Dialog)
        self.checkBoxDrawIsoCurve.setObjectName("checkBoxDrawIsoCurve")
        self.verticalLayout_2.addWidget(self.checkBoxDrawIsoCurve)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setMaximumSize(QtCore.QSize(95, 16777215))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.checkBoxSubtractAverageX = QtWidgets.QCheckBox(Dialog)
        self.checkBoxSubtractAverageX.setMaximumSize(QtCore.QSize(30, 16777215))
        self.checkBoxSubtractAverageX.setObjectName("checkBoxSubtractAverageX")
        self.horizontalLayout_6.addWidget(self.checkBoxSubtractAverageX)
        self.checkBoxSubtractAverageY = QtWidgets.QCheckBox(Dialog)
        self.checkBoxSubtractAverageY.setMaximumSize(QtCore.QSize(30, 16777215))
        self.checkBoxSubtractAverageY.setObjectName("checkBoxSubtractAverageY")
        self.horizontalLayout_6.addWidget(self.checkBoxSubtractAverageY)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_5 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radioButtonSliceHorizontal = QtWidgets.QRadioButton(Dialog)
        self.radioButtonSliceHorizontal.setChecked(False)
        self.radioButtonSliceHorizontal.setObjectName("radioButtonSliceHorizontal")
        self.horizontalLayout_5.addWidget(self.radioButtonSliceHorizontal)
        self.radioButtonSliceVertical = QtWidgets.QRadioButton(Dialog)
        self.radioButtonSliceVertical.setChecked(True)
        self.radioButtonSliceVertical.setObjectName("radioButtonSliceVertical")
        self.horizontalLayout_5.addWidget(self.radioButtonSliceVertical)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.label_4 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBoxMinimum = QtWidgets.QCheckBox(Dialog)
        self.checkBoxMinimum.setObjectName("checkBoxMinimum")
        self.horizontalLayout_3.addWidget(self.checkBoxMinimum)
        self.checkBoxMaximum = QtWidgets.QCheckBox(Dialog)
        self.checkBoxMaximum.setObjectName("checkBoxMaximum")
        self.horizontalLayout_3.addWidget(self.checkBoxMaximum)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.labelFit = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelFit.setFont(font)
        self.labelFit.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFit.setObjectName("labelFit")
        self.verticalLayout_2.addWidget(self.labelFit)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.verticalLayoutFitModel = QtWidgets.QVBoxLayout()
        self.verticalLayoutFitModel.setObjectName("verticalLayoutFitModel")
        self.verticalLayout_2.addLayout(self.verticalLayoutFitModel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.labelCoordinate = QtWidgets.QLabel(Dialog)
        self.labelCoordinate.setMinimumSize(QtCore.QSize(190, 0))
        self.labelCoordinate.setText("")
        self.labelCoordinate.setObjectName("labelCoordinate")
        self.verticalLayout_2.addWidget(self.labelCoordinate)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.plot2dzLabel.setText(_translate("Dialog", "TextLabel"))
        self.label_3.setText(_translate("Dialog", "Display"))
        self.label.setText(_translate("Dialog", "colormap"))
        self.checkBoxSwapxy.setText(_translate("Dialog", "Invert x/y"))
        self.checkBoxInvert.setText(_translate("Dialog", "Invert colormap"))
        self.checkBoxCrossHair.setText(_translate("Dialog", "cross hair (fastest without)"))
        self.checkBoxDrawIsoCurve.setText(_translate("Dialog", "Draw isocurve"))
        self.label_7.setText(_translate("Dialog", "Subtract average:"))
        self.checkBoxSubtractAverageX.setText(_translate("Dialog", "x"))
        self.checkBoxSubtractAverageY.setText(_translate("Dialog", "y"))
        self.label_2.setText(_translate("Dialog", "Data slicing"))
        self.label_5.setText(_translate("Dialog", "(double click)"))
        self.radioButtonSliceHorizontal.setText(_translate("Dialog", "horizontal"))
        self.radioButtonSliceVertical.setText(_translate("Dialog", "vertical"))
        self.label_4.setText(_translate("Dialog", "Extract"))
        self.checkBoxMinimum.setText(_translate("Dialog", "minimum"))
        self.checkBoxMaximum.setText(_translate("Dialog", "maximum"))
        self.labelFit.setText(_translate("Dialog", "Fit"))
        self.label_6.setText(_translate("Dialog", "fit model"))

from histogram_lut_widget import HistogramLUTWidget
from plot_widget import PlotWidget
