# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plot1d.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(987, 392)
        Dialog.setSizeGripEnabled(False)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = PlotWidget(Dialog)
        self.widget.setObjectName("widget")
        self.horizontalLayout.addWidget(self.widget)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelDisplay = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelDisplay.setFont(font)
        self.labelDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDisplay.setObjectName("labelDisplay")
        self.verticalLayout_2.addWidget(self.labelDisplay)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBoxLogX = QtWidgets.QCheckBox(Dialog)
        self.checkBoxLogX.setObjectName("checkBoxLogX")
        self.horizontalLayout_3.addWidget(self.checkBoxLogX)
        self.checkBoxLogY = QtWidgets.QCheckBox(Dialog)
        self.checkBoxLogY.setObjectName("checkBoxLogY")
        self.horizontalLayout_3.addWidget(self.checkBoxLogY)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.checkBoxSymbol = QtWidgets.QCheckBox(Dialog)
        self.checkBoxSymbol.setObjectName("checkBoxSymbol")
        self.verticalLayout_2.addWidget(self.checkBoxSymbol)
        self.checkBoxCrossHair = QtWidgets.QCheckBox(Dialog)
        self.checkBoxCrossHair.setChecked(False)
        self.checkBoxCrossHair.setObjectName("checkBoxCrossHair")
        self.verticalLayout_2.addWidget(self.checkBoxCrossHair)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.label_4 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.verticalLayoutPlotDataItem = QtWidgets.QVBoxLayout()
        self.verticalLayoutPlotDataItem.setObjectName("verticalLayoutPlotDataItem")
        self.radioButtonFitNone = QtWidgets.QRadioButton(Dialog)
        self.radioButtonFitNone.setEnabled(True)
        self.radioButtonFitNone.setChecked(True)
        self.radioButtonFitNone.setObjectName("radioButtonFitNone")
        self.verticalLayoutPlotDataItem.addWidget(self.radioButtonFitNone)
        self.verticalLayout_2.addLayout(self.verticalLayoutPlotDataItem)
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.labelFFT = QtWidgets.QLabel(Dialog)
        self.labelFFT.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelFFT.setFont(font)
        self.labelFFT.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFFT.setObjectName("labelFFT")
        self.verticalLayout_2.addWidget(self.labelFFT)
        self.horizontalLayoutFFT = QtWidgets.QHBoxLayout()
        self.horizontalLayoutFFT.setObjectName("horizontalLayoutFFT")
        self.pushButtonFFT = QtWidgets.QPushButton(Dialog)
        self.pushButtonFFT.setEnabled(False)
        self.pushButtonFFT.setObjectName("pushButtonFFT")
        self.horizontalLayoutFFT.addWidget(self.pushButtonFFT)
        self.pushButtonFFTnoDC = QtWidgets.QPushButton(Dialog)
        self.pushButtonFFTnoDC.setEnabled(False)
        self.pushButtonFFTnoDC.setObjectName("pushButtonFFTnoDC")
        self.horizontalLayoutFFT.addWidget(self.pushButtonFFTnoDC)
        self.pushButtonIFFT = QtWidgets.QPushButton(Dialog)
        self.pushButtonIFFT.setEnabled(False)
        self.pushButtonIFFT.setObjectName("pushButtonIFFT")
        self.horizontalLayoutFFT.addWidget(self.pushButtonIFFT)
        self.verticalLayout_2.addLayout(self.horizontalLayoutFFT)
        self.labelFit = QtWidgets.QLabel(Dialog)
        self.labelFit.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelFit.setFont(font)
        self.labelFit.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFit.setObjectName("labelFit")
        self.verticalLayout_2.addWidget(self.labelFit)
        self.labelFitModel = QtWidgets.QLabel(Dialog)
        self.labelFitModel.setEnabled(False)
        self.labelFitModel.setObjectName("labelFitModel")
        self.verticalLayout_2.addWidget(self.labelFitModel)
        self.verticalLayoutFitModel = QtWidgets.QVBoxLayout()
        self.verticalLayoutFitModel.setObjectName("verticalLayoutFitModel")
        self.verticalLayout_2.addLayout(self.verticalLayoutFitModel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.labelCoordinate = QtWidgets.QLabel(Dialog)
        self.labelCoordinate.setMinimumSize(QtCore.QSize(125, 0))
        self.labelCoordinate.setText("")
        self.labelCoordinate.setObjectName("labelCoordinate")
        self.verticalLayout_2.addWidget(self.labelCoordinate)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelDisplay.setText(_translate("Dialog", "Display"))
        self.checkBoxLogX.setText(_translate("Dialog", "log x"))
        self.checkBoxLogY.setText(_translate("Dialog", "log y"))
        self.checkBoxSymbol.setText(_translate("Dialog", "symbol (fastest without)"))
        self.checkBoxCrossHair.setText(_translate("Dialog", "cross hair (fastest without)"))
        self.label_4.setText(_translate("Dialog", "Select curve"))
        self.radioButtonFitNone.setText(_translate("Dialog", "None"))
        self.labelFFT.setText(_translate("Dialog", "FFT"))
        self.pushButtonFFT.setText(_translate("Dialog", "FFT"))
        self.pushButtonFFTnoDC.setText(_translate("Dialog", "FFT (no DC)"))
        self.pushButtonIFFT.setText(_translate("Dialog", "IFFT"))
        self.labelFit.setText(_translate("Dialog", "Fit"))
        self.labelFitModel.setText(_translate("Dialog", "Fit model"))

from plot_widget import PlotWidget
