# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\plot1d.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(987, 389)
        Dialog.setSizeGripEnabled(False)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = PlotWidget(Dialog)
        self.widget.setObjectName("widget")
        self.horizontalLayout.addWidget(self.widget)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(250, 16777215))
        self.tabWidget.setObjectName("tabWidget")
        self.tabInteraction = QtWidgets.QWidget()
        self.tabInteraction.setMinimumSize(QtCore.QSize(0, 0))
        self.tabInteraction.setObjectName("tabInteraction")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabInteraction)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelDisplay = QtWidgets.QLabel(self.tabInteraction)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelDisplay.setFont(font)
        self.labelDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDisplay.setObjectName("labelDisplay")
        self.verticalLayout_2.addWidget(self.labelDisplay)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBoxLogX = QtWidgets.QCheckBox(self.tabInteraction)
        self.checkBoxLogX.setObjectName("checkBoxLogX")
        self.horizontalLayout_3.addWidget(self.checkBoxLogX)
        self.checkBoxLogY = QtWidgets.QCheckBox(self.tabInteraction)
        self.checkBoxLogY.setObjectName("checkBoxLogY")
        self.horizontalLayout_3.addWidget(self.checkBoxLogY)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.checkBoxSymbol = QtWidgets.QCheckBox(self.tabInteraction)
        self.checkBoxSymbol.setObjectName("checkBoxSymbol")
        self.verticalLayout_2.addWidget(self.checkBoxSymbol)
        self.checkBoxCrossHair = QtWidgets.QCheckBox(self.tabInteraction)
        self.checkBoxCrossHair.setChecked(False)
        self.checkBoxCrossHair.setObjectName("checkBoxCrossHair")
        self.verticalLayout_2.addWidget(self.checkBoxCrossHair)
        self.line = QtWidgets.QFrame(self.tabInteraction)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.label_4 = QtWidgets.QLabel(self.tabInteraction)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.verticalLayoutPlotDataItem = QtWidgets.QVBoxLayout()
        self.verticalLayoutPlotDataItem.setObjectName("verticalLayoutPlotDataItem")
        self.radioButtonFitNone = QtWidgets.QRadioButton(self.tabInteraction)
        self.radioButtonFitNone.setEnabled(True)
        self.radioButtonFitNone.setChecked(True)
        self.radioButtonFitNone.setObjectName("radioButtonFitNone")
        self.verticalLayoutPlotDataItem.addWidget(self.radioButtonFitNone)
        self.verticalLayout_2.addLayout(self.verticalLayoutPlotDataItem)
        self.line_2 = QtWidgets.QFrame(self.tabInteraction)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.horizontalLayoutFFT = QtWidgets.QHBoxLayout()
        self.horizontalLayoutFFT.setObjectName("horizontalLayoutFFT")
        self.groupBoxFFT = QtWidgets.QGroupBox(self.tabInteraction)
        self.groupBoxFFT.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxFFT.setFont(font)
        self.groupBoxFFT.setObjectName("groupBoxFFT")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBoxFFT)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButtonFFT = QtWidgets.QRadioButton(self.groupBoxFFT)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.radioButtonFFT.setFont(font)
        self.radioButtonFFT.setObjectName("radioButtonFFT")
        self.buttonGroup = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButtonFFT)
        self.horizontalLayout_4.addWidget(self.radioButtonFFT)
        self.radioButtonFFTnoDC = QtWidgets.QRadioButton(self.groupBoxFFT)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.radioButtonFFTnoDC.setFont(font)
        self.radioButtonFFTnoDC.setObjectName("radioButtonFFTnoDC")
        self.buttonGroup.addButton(self.radioButtonFFTnoDC)
        self.horizontalLayout_4.addWidget(self.radioButtonFFTnoDC)
        self.radioButtonIFFT = QtWidgets.QRadioButton(self.groupBoxFFT)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.radioButtonIFFT.setFont(font)
        self.radioButtonIFFT.setObjectName("radioButtonIFFT")
        self.buttonGroup.addButton(self.radioButtonIFFT)
        self.horizontalLayout_4.addWidget(self.radioButtonIFFT)
        self.horizontalLayoutFFT.addWidget(self.groupBoxFFT, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.verticalLayout_2.addLayout(self.horizontalLayoutFFT)
        self.labelFit = QtWidgets.QLabel(self.tabInteraction)
        self.labelFit.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelFit.setFont(font)
        self.labelFit.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFit.setObjectName("labelFit")
        self.verticalLayout_2.addWidget(self.labelFit)
        self.labelFitModel = QtWidgets.QLabel(self.tabInteraction)
        self.labelFitModel.setEnabled(False)
        self.labelFitModel.setObjectName("labelFitModel")
        self.verticalLayout_2.addWidget(self.labelFitModel)
        self.verticalLayoutFitModel = QtWidgets.QVBoxLayout()
        self.verticalLayoutFitModel.setObjectName("verticalLayoutFitModel")
        self.verticalLayout_2.addLayout(self.verticalLayoutFitModel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.labelCoordinate = QtWidgets.QLabel(self.tabInteraction)
        self.labelCoordinate.setMinimumSize(QtCore.QSize(125, 0))
        self.labelCoordinate.setText("")
        self.labelCoordinate.setObjectName("labelCoordinate")
        self.verticalLayout_2.addWidget(self.labelCoordinate)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.tabInteraction, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelDisplay.setText(_translate("Dialog", "Display"))
        self.checkBoxLogX.setText(_translate("Dialog", "log x"))
        self.checkBoxLogY.setText(_translate("Dialog", "log y"))
        self.checkBoxSymbol.setText(_translate("Dialog", "symbol (fastest without)"))
        self.checkBoxCrossHair.setText(_translate("Dialog", "cross hair (fastest without)"))
        self.label_4.setText(_translate("Dialog", "Select curve"))
        self.radioButtonFitNone.setText(_translate("Dialog", "None"))
        self.groupBoxFFT.setTitle(_translate("Dialog", "FFT"))
        self.radioButtonFFT.setText(_translate("Dialog", "FFT"))
        self.radioButtonFFTnoDC.setText(_translate("Dialog", "FFT (no DC)"))
        self.radioButtonIFFT.setText(_translate("Dialog", "IFFT"))
        self.labelFit.setText(_translate("Dialog", "Fit"))
        self.labelFitModel.setText(_translate("Dialog", "Fit model"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabInteraction), _translate("Dialog", "Interaction"))

from plot_widget import PlotWidget
